version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.20
  aws-ecr: circleci/aws-ecr@6.7.1
  aws-ecs: circleci/aws-ecs@1.1.0

jobs:
  checkout-repo:
    docker:
      - image: circleci/node:14
    working_directory: ~/project
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - "*"

  audit-prototype:
    docker:
      - image: circleci/node:14
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            npx audit-ci --moderate

  test-prototype:
    docker:
      - image: circleci/node:12
    working_directory: ~/project
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          command: |
            npm install
            npm test

workflows:
  version: 2
  build-test-and-deploy-prototype:
    jobs:
      - checkout-repo:
          filters:
            branches:
              only: master

      - audit-prototype:
          requires:
            - checkout-repo
          filters:
            branches:
              only: master

      - test-prototype:
          requires:
            - audit-prototype
          filters:
            branches:
              only: master

      - aws-ecr/build-and-push-image:
          requires:
            - test-prototype
          repo: "${PROTOTYPE_ECR_REPO}"
          tag: "${CIRCLE_SHA1},latest"
          context: tfn-fdbt-core
          filters:
            branches:
              only: master

      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          family: "${PROTOTYPE_ECS_FAMILY}"
          name: deploy-prototype
          cluster-name: "${SITE_ECS_CLUSTER}"
          container-image-name-updates: "container=${PROTOTYPE_ECS_FAMILY},tag=${CIRCLE_SHA1}"
          context: tfn-fdbt-test
          verify-revision-is-deployed: true
          filters:
            branches:
              only: master
